// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailySalesStats = `-- name: GetDailySalesStats :many
SELECT date, total_revenue, total_orders, total_items_sold, avg_order_value, updated_at FROM daily_sales_stats
WHERE date >= $1 AND date <= $2
ORDER BY date ASC
LIMIT $3 OFFSET $4
`

type GetDailySalesStatsParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetDailySalesStats(ctx context.Context, arg GetDailySalesStatsParams) ([]DailySalesStat, error) {
	rows, err := q.db.Query(ctx, getDailySalesStats,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailySalesStat{}
	for rows.Next() {
		var i DailySalesStat
		if err := rows.Scan(
			&i.Date,
			&i.TotalRevenue,
			&i.TotalOrders,
			&i.TotalItemsSold,
			&i.AvgOrderValue,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalRevenue = `-- name: GetTotalRevenue :one
SELECT COALESCE(SUM(total_revenue), 0)::numeric FROM daily_sales_stats
`

func (q *Queries) GetTotalRevenue(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalRevenue)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertDailySalesStat = `-- name: UpsertDailySalesStat :exec
INSERT INTO daily_sales_stats (date, total_revenue, total_orders, total_items_sold, avg_order_value)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (date) DO UPDATE
SET total_revenue = EXCLUDED.total_revenue,
    total_orders = EXCLUDED.total_orders,
    total_items_sold = EXCLUDED.total_items_sold,
    avg_order_value = EXCLUDED.avg_order_value,
    updated_at = NOW()
`

type UpsertDailySalesStatParams struct {
	Date           pgtype.Date    `json:"date"`
	TotalRevenue   pgtype.Numeric `json:"total_revenue"`
	TotalOrders    int32          `json:"total_orders"`
	TotalItemsSold int32          `json:"total_items_sold"`
	AvgOrderValue  pgtype.Numeric `json:"avg_order_value"`
}

func (q *Queries) UpsertDailySalesStat(ctx context.Context, arg UpsertDailySalesStatParams) error {
	_, err := q.db.Exec(ctx, upsertDailySalesStat,
		arg.Date,
		arg.TotalRevenue,
		arg.TotalOrders,
		arg.TotalItemsSold,
		arg.AvgOrderValue,
	)
	return err
}
