// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, slug, parent_id, order_index, icon, image, is_active, show_in_nav, meta_title, meta_description, keywords, is_featured, og_image)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, name, slug, parent_id, order_index, icon, image, is_active, show_in_nav, meta_title, meta_description, keywords, is_featured, og_image, created_at, updated_at
`

type CreateCategoryParams struct {
	Name            *string     `json:"name"`
	Slug            *string     `json:"slug"`
	ParentID        pgtype.UUID `json:"parent_id"`
	OrderIndex      int32       `json:"order_index"`
	Icon            *string     `json:"icon"`
	Image           *string     `json:"image"`
	IsActive        bool        `json:"is_active"`
	ShowInNav       bool        `json:"show_in_nav"`
	MetaTitle       *string     `json:"meta_title"`
	MetaDescription *string     `json:"meta_description"`
	Keywords        *string     `json:"keywords"`
	IsFeatured      bool        `json:"is_featured"`
	OgImage         *string     `json:"og_image"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Slug,
		arg.ParentID,
		arg.OrderIndex,
		arg.Icon,
		arg.Image,
		arg.IsActive,
		arg.ShowInNav,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.Keywords,
		arg.IsFeatured,
		arg.OgImage,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.OrderIndex,
		&i.Icon,
		&i.Image,
		&i.IsActive,
		&i.ShowInNav,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Keywords,
		&i.IsFeatured,
		&i.OgImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getActiveChildCategories = `-- name: GetActiveChildCategories :many
SELECT id, name, slug, parent_id, order_index, icon, image, is_active, show_in_nav, meta_title, meta_description, keywords, is_featured, og_image, created_at, updated_at FROM categories 
WHERE parent_id = $1 AND is_active = true AND show_in_nav = true 
ORDER BY order_index ASC
`

func (q *Queries) GetActiveChildCategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getActiveChildCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.OrderIndex,
			&i.Icon,
			&i.Image,
			&i.IsActive,
			&i.ShowInNav,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.Keywords,
			&i.IsFeatured,
			&i.OgImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveNavCategories = `-- name: GetActiveNavCategories :many
SELECT id, name, slug, parent_id, order_index, icon, image, is_active, show_in_nav, meta_title, meta_description, keywords, is_featured, og_image, created_at, updated_at FROM categories 
WHERE parent_id IS NULL AND is_active = true AND show_in_nav = true 
ORDER BY order_index ASC
`

func (q *Queries) GetActiveNavCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getActiveNavCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.OrderIndex,
			&i.Icon,
			&i.Image,
			&i.IsActive,
			&i.ShowInNav,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.Keywords,
			&i.IsFeatured,
			&i.OgImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, name, slug, parent_id, order_index, icon, image, is_active, show_in_nav, meta_title, meta_description, keywords, is_featured, og_image, created_at, updated_at FROM categories ORDER BY order_index ASC
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.OrderIndex,
			&i.Icon,
			&i.Image,
			&i.IsActive,
			&i.ShowInNav,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.Keywords,
			&i.IsFeatured,
			&i.OgImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesByIDs = `-- name: GetCategoriesByIDs :many
SELECT id, name, slug, parent_id, order_index, icon, image, is_active, show_in_nav, meta_title, meta_description, keywords, is_featured, og_image, created_at, updated_at FROM categories WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetCategoriesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.OrderIndex,
			&i.Icon,
			&i.Image,
			&i.IsActive,
			&i.ShowInNav,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.Keywords,
			&i.IsFeatured,
			&i.OgImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesFlat = `-- name: GetCategoriesFlat :many
SELECT id, name, slug, parent_id, order_index, icon, image, is_active, show_in_nav, meta_title, meta_description, keywords, is_featured, og_image, created_at, updated_at FROM categories 
WHERE ($1::boolean IS NULL OR is_active = $1)
ORDER BY name ASC
`

func (q *Queries) GetCategoriesFlat(ctx context.Context, isActive *bool) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesFlat, isActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.OrderIndex,
			&i.Icon,
			&i.Image,
			&i.IsActive,
			&i.ShowInNav,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.Keywords,
			&i.IsFeatured,
			&i.OgImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, slug, parent_id, order_index, icon, image, is_active, show_in_nav, meta_title, meta_description, keywords, is_featured, og_image, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.OrderIndex,
		&i.Icon,
		&i.Image,
		&i.IsActive,
		&i.ShowInNav,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Keywords,
		&i.IsFeatured,
		&i.OgImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, parent_id, order_index, icon, image, is_active, show_in_nav, meta_title, meta_description, keywords, is_featured, og_image, created_at, updated_at FROM categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug *string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.OrderIndex,
		&i.Icon,
		&i.Image,
		&i.IsActive,
		&i.ShowInNav,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Keywords,
		&i.IsFeatured,
		&i.OgImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChildCategories = `-- name: GetChildCategories :many
SELECT id, name, slug, parent_id, order_index, icon, image, is_active, show_in_nav, meta_title, meta_description, keywords, is_featured, og_image, created_at, updated_at FROM categories WHERE parent_id = $1 ORDER BY order_index ASC
`

func (q *Queries) GetChildCategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getChildCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.OrderIndex,
			&i.Icon,
			&i.Image,
			&i.IsActive,
			&i.ShowInNav,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.Keywords,
			&i.IsFeatured,
			&i.OgImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootCategories = `-- name: GetRootCategories :many
SELECT id, name, slug, parent_id, order_index, icon, image, is_active, show_in_nav, meta_title, meta_description, keywords, is_featured, og_image, created_at, updated_at FROM categories WHERE parent_id IS NULL ORDER BY order_index ASC
`

func (q *Queries) GetRootCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getRootCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.OrderIndex,
			&i.Icon,
			&i.Image,
			&i.IsActive,
			&i.ShowInNav,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.Keywords,
			&i.IsFeatured,
			&i.OgImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, slug = $3, parent_id = $4, order_index = $5, icon = $6, image = $7, 
    is_active = $8, show_in_nav = $9, meta_title = $10, meta_description = $11, keywords = $12, is_featured = $13, og_image = $14
WHERE id = $1
RETURNING id, name, slug, parent_id, order_index, icon, image, is_active, show_in_nav, meta_title, meta_description, keywords, is_featured, og_image, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            *string     `json:"name"`
	Slug            *string     `json:"slug"`
	ParentID        pgtype.UUID `json:"parent_id"`
	OrderIndex      int32       `json:"order_index"`
	Icon            *string     `json:"icon"`
	Image           *string     `json:"image"`
	IsActive        bool        `json:"is_active"`
	ShowInNav       bool        `json:"show_in_nav"`
	MetaTitle       *string     `json:"meta_title"`
	MetaDescription *string     `json:"meta_description"`
	Keywords        *string     `json:"keywords"`
	IsFeatured      bool        `json:"is_featured"`
	OgImage         *string     `json:"og_image"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.ParentID,
		arg.OrderIndex,
		arg.Icon,
		arg.Image,
		arg.IsActive,
		arg.ShowInNav,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.Keywords,
		arg.IsFeatured,
		arg.OgImage,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.OrderIndex,
		&i.Icon,
		&i.Image,
		&i.IsActive,
		&i.ShowInNav,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Keywords,
		&i.IsFeatured,
		&i.OgImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategoryOrder = `-- name: UpdateCategoryOrder :exec
UPDATE categories SET order_index = $2, parent_id = $3 WHERE id = $1
`

type UpdateCategoryOrderParams struct {
	ID         pgtype.UUID `json:"id"`
	OrderIndex int32       `json:"order_index"`
	ParentID   pgtype.UUID `json:"parent_id"`
}

func (q *Queries) UpdateCategoryOrder(ctx context.Context, arg UpdateCategoryOrderParams) error {
	_, err := q.db.Exec(ctx, updateCategoryOrder, arg.ID, arg.OrderIndex, arg.ParentID)
	return err
}
