// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProductToCollection = `-- name: AddProductToCollection :exec
INSERT INTO product_collections (product_id, collection_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProductToCollectionParams struct {
	ProductID    pgtype.UUID `json:"product_id"`
	CollectionID pgtype.UUID `json:"collection_id"`
}

func (q *Queries) AddProductToCollection(ctx context.Context, arg AddProductToCollectionParams) error {
	_, err := q.db.Exec(ctx, addProductToCollection, arg.ProductID, arg.CollectionID)
	return err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (title, slug, description, image, story, is_active, meta_title, meta_description, meta_keywords, og_image)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, title, slug, description, image, story, is_active, created_at, updated_at, meta_title, meta_description, meta_keywords, og_image
`

type CreateCollectionParams struct {
	Title           string  `json:"title"`
	Slug            string  `json:"slug"`
	Description     *string `json:"description"`
	Image           *string `json:"image"`
	Story           *string `json:"story"`
	IsActive        bool    `json:"is_active"`
	MetaTitle       *string `json:"meta_title"`
	MetaDescription *string `json:"meta_description"`
	MetaKeywords    *string `json:"meta_keywords"`
	OgImage         *string `json:"og_image"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Image,
		arg.Story,
		arg.IsActive,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.MetaKeywords,
		arg.OgImage,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Story,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.OgImage,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getActiveCollections = `-- name: GetActiveCollections :many
SELECT id, title, slug, description, image, story, is_active, created_at, updated_at, meta_title, meta_description, meta_keywords, og_image FROM collections WHERE is_active = true ORDER BY created_at DESC
`

func (q *Queries) GetActiveCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.Query(ctx, getActiveCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Image,
			&i.Story,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.MetaKeywords,
			&i.OgImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCollections = `-- name: GetAllCollections :many
SELECT id, title, slug, description, image, story, is_active, created_at, updated_at, meta_title, meta_description, meta_keywords, og_image FROM collections ORDER BY created_at DESC
`

func (q *Queries) GetAllCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.Query(ctx, getAllCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Image,
			&i.Story,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.MetaKeywords,
			&i.OgImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, title, slug, description, image, story, is_active, created_at, updated_at, meta_title, meta_description, meta_keywords, og_image FROM collections WHERE id = $1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id pgtype.UUID) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Story,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.OgImage,
	)
	return i, err
}

const getCollectionBySlug = `-- name: GetCollectionBySlug :one
SELECT id, title, slug, description, image, story, is_active, created_at, updated_at, meta_title, meta_description, meta_keywords, og_image FROM collections WHERE slug = $1
`

func (q *Queries) GetCollectionBySlug(ctx context.Context, slug string) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionBySlug, slug)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Story,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.OgImage,
	)
	return i, err
}

const getProductIDsForCollection = `-- name: GetProductIDsForCollection :many
SELECT product_id FROM product_collections WHERE collection_id = $1
`

func (q *Queries) GetProductIDsForCollection(ctx context.Context, collectionID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getProductIDsForCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var product_id pgtype.UUID
		if err := rows.Scan(&product_id); err != nil {
			return nil, err
		}
		items = append(items, product_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProductFromCollection = `-- name: RemoveProductFromCollection :exec
DELETE FROM product_collections WHERE product_id = $1 AND collection_id = $2
`

type RemoveProductFromCollectionParams struct {
	ProductID    pgtype.UUID `json:"product_id"`
	CollectionID pgtype.UUID `json:"collection_id"`
}

func (q *Queries) RemoveProductFromCollection(ctx context.Context, arg RemoveProductFromCollectionParams) error {
	_, err := q.db.Exec(ctx, removeProductFromCollection, arg.ProductID, arg.CollectionID)
	return err
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET title = $2, slug = $3, description = $4, image = $5, story = $6, is_active = $7,
    meta_title = $8, meta_description = $9, meta_keywords = $10, og_image = $11
WHERE id = $1
RETURNING id, title, slug, description, image, story, is_active, created_at, updated_at, meta_title, meta_description, meta_keywords, og_image
`

type UpdateCollectionParams struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Slug            string      `json:"slug"`
	Description     *string     `json:"description"`
	Image           *string     `json:"image"`
	Story           *string     `json:"story"`
	IsActive        bool        `json:"is_active"`
	MetaTitle       *string     `json:"meta_title"`
	MetaDescription *string     `json:"meta_description"`
	MetaKeywords    *string     `json:"meta_keywords"`
	OgImage         *string     `json:"og_image"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Image,
		arg.Story,
		arg.IsActive,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.MetaKeywords,
		arg.OgImage,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Story,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.OgImage,
	)
	return i, err
}
