// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShippingZone = `-- name: CreateShippingZone :one
INSERT INTO shipping_zones (key, label, cost, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, key, label, cost, is_active, created_at, updated_at
`

type CreateShippingZoneParams struct {
	Key      string         `json:"key"`
	Label    string         `json:"label"`
	Cost     pgtype.Numeric `json:"cost"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) CreateShippingZone(ctx context.Context, arg CreateShippingZoneParams) (ShippingZone, error) {
	row := q.db.QueryRow(ctx, createShippingZone,
		arg.Key,
		arg.Label,
		arg.Cost,
		arg.IsActive,
	)
	var i ShippingZone
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShippingZone = `-- name: DeleteShippingZone :exec
DELETE FROM shipping_zones WHERE id = $1
`

func (q *Queries) DeleteShippingZone(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteShippingZone, id)
	return err
}

const getActiveShippingZones = `-- name: GetActiveShippingZones :many
SELECT id, key, label, cost, is_active, created_at, updated_at FROM shipping_zones WHERE is_active = TRUE ORDER BY id ASC
`

func (q *Queries) GetActiveShippingZones(ctx context.Context) ([]ShippingZone, error) {
	rows, err := q.db.Query(ctx, getActiveShippingZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingZone{}
	for rows.Next() {
		var i ShippingZone
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.Cost,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllShippingZones = `-- name: GetAllShippingZones :many
SELECT id, key, label, cost, is_active, created_at, updated_at FROM shipping_zones ORDER BY id ASC
`

func (q *Queries) GetAllShippingZones(ctx context.Context) ([]ShippingZone, error) {
	rows, err := q.db.Query(ctx, getAllShippingZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingZone{}
	for rows.Next() {
		var i ShippingZone
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.Cost,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShippingZoneByID = `-- name: GetShippingZoneByID :one
SELECT id, key, label, cost, is_active, created_at, updated_at FROM shipping_zones WHERE id = $1
`

func (q *Queries) GetShippingZoneByID(ctx context.Context, id int32) (ShippingZone, error) {
	row := q.db.QueryRow(ctx, getShippingZoneByID, id)
	var i ShippingZone
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShippingZoneByKey = `-- name: GetShippingZoneByKey :one
SELECT id, key, label, cost, is_active, created_at, updated_at FROM shipping_zones WHERE key = $1 AND is_active = TRUE
`

func (q *Queries) GetShippingZoneByKey(ctx context.Context, key string) (ShippingZone, error) {
	row := q.db.QueryRow(ctx, getShippingZoneByKey, key)
	var i ShippingZone
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShippingZone = `-- name: UpdateShippingZone :one
UPDATE shipping_zones
SET label = $2, cost = $3, is_active = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, key, label, cost, is_active, created_at, updated_at
`

type UpdateShippingZoneParams struct {
	ID       int32          `json:"id"`
	Label    string         `json:"label"`
	Cost     pgtype.Numeric `json:"cost"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) UpdateShippingZone(ctx context.Context, arg UpdateShippingZoneParams) (ShippingZone, error) {
	row := q.db.QueryRow(ctx, updateShippingZone,
		arg.ID,
		arg.Label,
		arg.Cost,
		arg.IsActive,
	)
	var i ShippingZone
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShippingZoneCost = `-- name: UpdateShippingZoneCost :exec
UPDATE shipping_zones SET cost = $2, updated_at = CURRENT_TIMESTAMP WHERE key = $1
`

type UpdateShippingZoneCostParams struct {
	Key  string         `json:"key"`
	Cost pgtype.Numeric `json:"cost"`
}

func (q *Queries) UpdateShippingZoneCost(ctx context.Context, arg UpdateShippingZoneCostParams) error {
	_, err := q.db.Exec(ctx, updateShippingZoneCost, arg.Key, arg.Cost)
	return err
}
