// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	Label        *string          `json:"label"`
	ContactEmail *string          `json:"contact_email"`
	Phone        *string          `json:"phone"`
	FirstName    *string          `json:"first_name"`
	LastName     *string          `json:"last_name"`
	DeliveryZone *string          `json:"delivery_zone"`
	Division     *string          `json:"division"`
	District     *string          `json:"district"`
	Thana        *string          `json:"thana"`
	AddressLine  *string          `json:"address_line"`
	Landmark     *string          `json:"landmark"`
	PostalCode   *string          `json:"postal_code"`
	IsDefault    bool             `json:"is_default"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Cart struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type CartItem struct {
	ID        pgtype.UUID `json:"id"`
	CartID    pgtype.UUID `json:"cart_id"`
	ProductID pgtype.UUID `json:"product_id"`
	VariantID pgtype.UUID `json:"variant_id"`
	Quantity  int32       `json:"quantity"`
}

type Category struct {
	ID              pgtype.UUID      `json:"id"`
	Name            *string          `json:"name"`
	Slug            *string          `json:"slug"`
	ParentID        pgtype.UUID      `json:"parent_id"`
	OrderIndex      int32            `json:"order_index"`
	Icon            *string          `json:"icon"`
	Image           *string          `json:"image"`
	IsActive        bool             `json:"is_active"`
	ShowInNav       bool             `json:"show_in_nav"`
	MetaTitle       *string          `json:"meta_title"`
	MetaDescription *string          `json:"meta_description"`
	Keywords        *string          `json:"keywords"`
	IsFeatured      bool             `json:"is_featured"`
	OgImage         *string          `json:"og_image"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type Collection struct {
	ID              pgtype.UUID      `json:"id"`
	Title           string           `json:"title"`
	Slug            string           `json:"slug"`
	Description     *string          `json:"description"`
	Image           *string          `json:"image"`
	Story           *string          `json:"story"`
	IsActive        bool             `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	MetaTitle       *string          `json:"meta_title"`
	MetaDescription *string          `json:"meta_description"`
	MetaKeywords    *string          `json:"meta_keywords"`
	OgImage         *string          `json:"og_image"`
}

type ContentBlock struct {
	ID         pgtype.UUID        `json:"id"`
	SectionKey string             `json:"section_key"`
	Content    []byte             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	StartAt    pgtype.Timestamp   `json:"start_at"`
	EndAt      pgtype.Timestamp   `json:"end_at"`
	IsActive   *bool              `json:"is_active"`
}

type Coupon struct {
	ID         pgtype.UUID      `json:"id"`
	Code       string           `json:"code"`
	Type       string           `json:"type"`
	Value      pgtype.Numeric   `json:"value"`
	MinSpend   pgtype.Numeric   `json:"min_spend"`
	UsageLimit *int32           `json:"usage_limit"`
	UsedCount  *int32           `json:"used_count"`
	StartAt    pgtype.Timestamp `json:"start_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	IsActive   *bool            `json:"is_active"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type DailySalesStat struct {
	Date           pgtype.Date      `json:"date"`
	TotalRevenue   pgtype.Numeric   `json:"total_revenue"`
	TotalOrders    int32            `json:"total_orders"`
	TotalItemsSold int32            `json:"total_items_sold"`
	AvgOrderValue  pgtype.Numeric   `json:"avg_order_value"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type InventoryLog struct {
	ID           int32            `json:"id"`
	ProductID    pgtype.UUID      `json:"product_id"`
	VariantID    pgtype.UUID      `json:"variant_id"`
	ChangeAmount int32            `json:"change_amount"`
	Reason       string           `json:"reason"`
	ReferenceID  string           `json:"reference_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID              pgtype.UUID      `json:"id"`
	UserID          pgtype.UUID      `json:"user_id"`
	Status          string           `json:"status"`
	TotalAmount     pgtype.Numeric   `json:"total_amount"`
	ShippingAddress []byte           `json:"shipping_address"`
	PaymentMethod   *string          `json:"payment_method"`
	PaymentStatus   *string          `json:"payment_status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	PaidAmount      pgtype.Numeric   `json:"paid_amount"`
	PaymentDetails  []byte           `json:"payment_details"`
	IsPreorder      bool             `json:"is_preorder"`
	RefundedAmount  pgtype.Numeric   `json:"refunded_amount"`
	ShippingFee     pgtype.Numeric   `json:"shipping_fee"`
}

type OrderHistory struct {
	ID             pgtype.UUID        `json:"id"`
	OrderID        pgtype.UUID        `json:"order_id"`
	PreviousStatus *string            `json:"previous_status"`
	NewStatus      string             `json:"new_status"`
	Reason         *string            `json:"reason"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OrderItem struct {
	ID        pgtype.UUID    `json:"id"`
	OrderID   pgtype.UUID    `json:"order_id"`
	ProductID pgtype.UUID    `json:"product_id"`
	VariantID pgtype.UUID    `json:"variant_id"`
	Quantity  int32          `json:"quantity"`
	Price     pgtype.Numeric `json:"price"`
}

type Product struct {
	ID              pgtype.UUID      `json:"id"`
	Name            string           `json:"name"`
	Slug            string           `json:"slug"`
	Description     *string          `json:"description"`
	BasePrice       pgtype.Numeric   `json:"base_price"`
	SalePrice       pgtype.Numeric   `json:"sale_price"`
	StockStatus     *string          `json:"stock_status"`
	IsFeatured      bool             `json:"is_featured"`
	IsActive        bool             `json:"is_active"`
	Media           []byte           `json:"media"`
	Attributes      []byte           `json:"attributes"`
	Specifications  []byte           `json:"specifications"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	SearchVector    interface{}      `json:"search_vector"`
	MetaTitle       *string          `json:"meta_title"`
	MetaDescription *string          `json:"meta_description"`
	MetaKeywords    *string          `json:"meta_keywords"`
	OgImage         *string          `json:"og_image"`
	Brand           *string          `json:"brand"`
	Tags            []string         `json:"tags"`
	WarrantyInfo    []byte           `json:"warranty_info"`
}

type ProductCategory struct {
	ProductID  pgtype.UUID `json:"product_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type ProductCollection struct {
	ProductID    pgtype.UUID `json:"product_id"`
	CollectionID pgtype.UUID `json:"collection_id"`
}

type RefreshToken struct {
	ID        pgtype.UUID      `json:"id"`
	Token     string           `json:"token"`
	UserID    pgtype.UUID      `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Revoked   bool             `json:"revoked"`
	Device    *string          `json:"device"`
}

type Refund struct {
	ID           pgtype.UUID      `json:"id"`
	OrderID      pgtype.UUID      `json:"order_id"`
	Amount       pgtype.Numeric   `json:"amount"`
	Reason       *string          `json:"reason"`
	RestockItems bool             `json:"restock_items"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	CreatedBy    pgtype.UUID      `json:"created_by"`
}

type Review struct {
	ID        pgtype.UUID      `json:"id"`
	ProductID pgtype.UUID      `json:"product_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Rating    int32            `json:"rating"`
	Comment   *string          `json:"comment"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type ShippingZone struct {
	ID        int32            `json:"id"`
	Key       string           `json:"key"`
	Label     string           `json:"label"`
	Cost      pgtype.Numeric   `json:"cost"`
	IsActive  bool             `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Email     string           `json:"email"`
	Role      string           `json:"role"`
	FirstName *string          `json:"first_name"`
	LastName  *string          `json:"last_name"`
	Avatar    *string          `json:"avatar"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Phone     *string          `json:"phone"`
}

type Variant struct {
	ID                pgtype.UUID      `json:"id"`
	ProductID         pgtype.UUID      `json:"product_id"`
	Name              string           `json:"name"`
	Stock             int32            `json:"stock"`
	Sku               *string          `json:"sku"`
	Attributes        []byte           `json:"attributes"`
	Price             pgtype.Numeric   `json:"price"`
	SalePrice         pgtype.Numeric   `json:"sale_price"`
	Images            []string         `json:"images"`
	Weight            pgtype.Numeric   `json:"weight"`
	Dimensions        []byte           `json:"dimensions"`
	Barcode           *string          `json:"barcode"`
	LowStockThreshold int32            `json:"low_stock_threshold"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type Wishlist struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type WishlistItem struct {
	ID         pgtype.UUID      `json:"id"`
	WishlistID pgtype.UUID      `json:"wishlist_id"`
	ProductID  pgtype.UUID      `json:"product_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}
