// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddProductCategory(ctx context.Context, arg AddProductCategoryParams) error
	AddProductCollection(ctx context.Context, arg AddProductCollectionParams) error
	AddProductToCollection(ctx context.Context, arg AddProductToCollectionParams) error
	AddWishlistItem(ctx context.Context, arg AddWishlistItemParams) error
	AtomicRemoveCartItem(ctx context.Context, arg AtomicRemoveCartItemParams) error
	CheckItemInWishlist(ctx context.Context, arg CheckItemInWishlistParams) (bool, error)
	ClearCart(ctx context.Context, cartID pgtype.UUID) error
	ClearProductCategories(ctx context.Context, productID pgtype.UUID) error
	ClearProductCollections(ctx context.Context, productID pgtype.UUID) error
	CountAllVariantsWithProduct(ctx context.Context, arg CountAllVariantsWithProductParams) (int64, error)
	CountCoupons(ctx context.Context) (int64, error)
	CountInventoryLogs(ctx context.Context, dollar_1 pgtype.UUID) (int64, error)
	CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountProductsWithCategoryFilter(ctx context.Context, arg CountProductsWithCategoryFilterParams) (int64, error)
	CountSearchProducts(ctx context.Context, arg CountSearchProductsParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateCart(ctx context.Context, userID pgtype.UUID) (Cart, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error)
	CreateInventoryLog(ctx context.Context, arg CreateInventoryLogParams) (InventoryLog, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderHistory(ctx context.Context, arg CreateOrderHistoryParams) (OrderHistory, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateShippingZone(ctx context.Context, arg CreateShippingZoneParams) (ShippingZone, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error)
	CreateWishlist(ctx context.Context, userID pgtype.UUID) (Wishlist, error)
	DeleteAddress(ctx context.Context, arg DeleteAddressParams) error
	DeleteCategory(ctx context.Context, id pgtype.UUID) error
	DeleteCollection(ctx context.Context, id pgtype.UUID) error
	DeleteCoupon(ctx context.Context, id pgtype.UUID) error
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	DeleteReview(ctx context.Context, id pgtype.UUID) error
	DeleteShippingZone(ctx context.Context, id int32) error
	DeleteVariant(ctx context.Context, id pgtype.UUID) error
	DeleteVariantsByProductID(ctx context.Context, productID pgtype.UUID) error
	GetActiveChildCategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error)
	GetActiveCollections(ctx context.Context) ([]Collection, error)
	GetActiveContentBlock(ctx context.Context, sectionKey string) (ContentBlock, error)
	GetActiveNavCategories(ctx context.Context) ([]Category, error)
	GetActiveShippingZones(ctx context.Context) ([]ShippingZone, error)
	GetAddressesByUserID(ctx context.Context, userID pgtype.UUID) ([]Address, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAllCollections(ctx context.Context) ([]Collection, error)
	GetAllOrders(ctx context.Context, arg GetAllOrdersParams) ([]GetAllOrdersRow, error)
	GetAllShippingZones(ctx context.Context) ([]ShippingZone, error)
	GetAllVariantsWithProduct(ctx context.Context, arg GetAllVariantsWithProductParams) ([]GetAllVariantsWithProductRow, error)
	GetCartByUserID(ctx context.Context, userID pgtype.UUID) (Cart, error)
	GetCartItemByProductID(ctx context.Context, arg GetCartItemByProductIDParams) (CartItem, error)
	GetCartItems(ctx context.Context, cartID pgtype.UUID) ([]GetCartItemsRow, error)
	GetCartWithItems(ctx context.Context, userID pgtype.UUID) ([]GetCartWithItemsRow, error)
	GetCategoriesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Category, error)
	GetCategoriesFlat(ctx context.Context, isActive *bool) ([]Category, error)
	GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug *string) (Category, error)
	GetCategoryIDsForProduct(ctx context.Context, productID pgtype.UUID) ([]pgtype.UUID, error)
	GetCategoryIDsForProducts(ctx context.Context, dollar_1 []pgtype.UUID) ([]ProductCategory, error)
	GetChildCategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error)
	GetCollectionByID(ctx context.Context, id pgtype.UUID) (Collection, error)
	GetCollectionBySlug(ctx context.Context, slug string) (Collection, error)
	GetCollectionIDsForProduct(ctx context.Context, productID pgtype.UUID) ([]pgtype.UUID, error)
	GetCollectionIDsForProducts(ctx context.Context, dollar_1 []pgtype.UUID) ([]ProductCollection, error)
	GetCollectionsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Collection, error)
	GetContentBlockByKey(ctx context.Context, sectionKey string) (ContentBlock, error)
	GetCouponByCode(ctx context.Context, code string) (Coupon, error)
	GetCouponByID(ctx context.Context, id pgtype.UUID) (Coupon, error)
	// Top customers by lifetime value (parameterized date range and limit)
	GetCustomerLTV(ctx context.Context, arg GetCustomerLTVParams) ([]GetCustomerLTVRow, error)
	// New vs Returning customers (parameterized date range)
	GetCustomerRetention(ctx context.Context, arg GetCustomerRetentionParams) (GetCustomerRetentionRow, error)
	// Revenue aggregation by day with parameterized date range
	GetDailySales(ctx context.Context, arg GetDailySalesParams) ([]GetDailySalesRow, error)
	GetDailySalesStats(ctx context.Context, arg GetDailySalesStatsParams) ([]DailySalesStat, error)
	// Variants with no sales in X days (parameterized)
	GetDeadStockProducts(ctx context.Context, arg GetDeadStockProductsParams) ([]GetDeadStockProductsRow, error)
	GetInventoryLogs(ctx context.Context, arg GetInventoryLogsParams) ([]InventoryLog, error)
	// L9 Dashboard/Stats Queries: Fully Parameterized (Zero Hardcoded Values)
	// All date ranges, thresholds, limits controlled by frontend via query params
	// Variants below threshold (parameterized - no hardcoded limit)
	GetLowStockProducts(ctx context.Context, arg GetLowStockProductsParams) ([]GetLowStockProductsRow, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrderHistory(ctx context.Context, orderID pgtype.UUID) ([]GetOrderHistoryRow, error)
	GetOrderItems(ctx context.Context, orderID pgtype.UUID) ([]GetOrderItemsRow, error)
	GetOrdersByUserID(ctx context.Context, userID pgtype.UUID) ([]Order, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error)
	GetProductBySlug(ctx context.Context, slug string) (Product, error)
	GetProductIDsForCollection(ctx context.Context, collectionID pgtype.UUID) ([]pgtype.UUID, error)
	GetProductStats(ctx context.Context) (GetProductStatsRow, error)
	GetProducts(ctx context.Context, arg GetProductsParams) ([]Product, error)
	GetProductsForCollection(ctx context.Context, collectionID pgtype.UUID) ([]Product, error)
	GetProductsWithCategoryFilter(ctx context.Context, arg GetProductsWithCategoryFilterParams) ([]Product, error)
	GetProductsWithPriceRange(ctx context.Context, arg GetProductsWithPriceRangeParams) ([]Product, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetRefundsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]GetRefundsByOrderIDRow, error)
	// Key performance indicators for a parameterized date range
	GetRevenueKPIs(ctx context.Context, arg GetRevenueKPIsParams) (GetRevenueKPIsRow, error)
	GetReviewByID(ctx context.Context, id pgtype.UUID) (Review, error)
	GetReviewsByProductID(ctx context.Context, productID pgtype.UUID) ([]GetReviewsByProductIDRow, error)
	GetRootCategories(ctx context.Context) ([]Category, error)
	GetShippingZoneByID(ctx context.Context, id int32) (ShippingZone, error)
	GetShippingZoneByKey(ctx context.Context, key string) (ShippingZone, error)
	// Best-selling products by quantity (parameterized date range and limit)
	GetTopSellingProducts(ctx context.Context, arg GetTopSellingProductsParams) ([]GetTopSellingProductsRow, error)
	GetTotalRevenue(ctx context.Context) (pgtype.Numeric, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserReviewForProduct(ctx context.Context, arg GetUserReviewForProductParams) (Review, error)
	GetVariantByID(ctx context.Context, id pgtype.UUID) (Variant, error)
	GetVariantsByProductID(ctx context.Context, productID pgtype.UUID) ([]Variant, error)
	GetVariantsByProductIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Variant, error)
	GetWishlistByUserID(ctx context.Context, userID pgtype.UUID) (Wishlist, error)
	GetWishlistItems(ctx context.Context, wishlistID pgtype.UUID) ([]GetWishlistItemsRow, error)
	HasPurchasedProduct(ctx context.Context, arg HasPurchasedProductParams) (bool, error)
	// L9 Optimization: Atomic increment with optimistic concurrency check if needed.
	// We rely on db-level atomicity here.
	IncrementCouponUsage(ctx context.Context, id pgtype.UUID) error
	ListCategorySlugs(ctx context.Context) ([]ListCategorySlugsRow, error)
	ListCollectionSlugs(ctx context.Context) ([]ListCollectionSlugsRow, error)
	ListCoupons(ctx context.Context, arg ListCouponsParams) ([]Coupon, error)
	ListProductSlugs(ctx context.Context) ([]ListProductSlugsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveProductCategory(ctx context.Context, arg RemoveProductCategoryParams) error
	RemoveProductCollection(ctx context.Context, arg RemoveProductCollectionParams) error
	RemoveProductFromCollection(ctx context.Context, arg RemoveProductFromCollectionParams) error
	RemoveWishlistItem(ctx context.Context, arg RemoveWishlistItemParams) error
	RevokeRefreshToken(ctx context.Context, token string) error
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (RefreshToken, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error)
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryOrder(ctx context.Context, arg UpdateCategoryOrderParams) error
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error)
	UpdateContentBlockSchedule(ctx context.Context, arg UpdateContentBlockScheduleParams) error
	UpdateCoupon(ctx context.Context, arg UpdateCouponParams) error
	UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) error
	UpdateOrderRefundedAmount(ctx context.Context, arg UpdateOrderRefundedAmountParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) error
	UpdateShippingZone(ctx context.Context, arg UpdateShippingZoneParams) (ShippingZone, error)
	UpdateShippingZoneCost(ctx context.Context, arg UpdateShippingZoneCostParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateVariant(ctx context.Context, arg UpdateVariantParams) (Variant, error)
	UpdateVariantStock(ctx context.Context, arg UpdateVariantStockParams) (int64, error)
	// L9 FIX: Simplified atomic upsert without expression-based conflict target
	UpsertCartItemAtomic(ctx context.Context, arg UpsertCartItemAtomicParams) ([]UpsertCartItemAtomicRow, error)
	UpsertContentBlock(ctx context.Context, arg UpsertContentBlockParams) (ContentBlock, error)
	UpsertDailySalesStat(ctx context.Context, arg UpsertDailySalesStatParams) error
	// L9 Optimization: Single-pass validation logic pushed to DB.
	// Returns the coupon if valid, or a status reason if not.
	// Uses covering indexes on (code) and partial indexes on (is_active) where applicable.
	ValidateCoupon(ctx context.Context, arg ValidateCouponParams) (ValidateCouponRow, error)
}

var _ Querier = (*Queries)(nil)
