// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (product_id, user_id, rating, comment)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, user_id, rating, comment, created_at
`

type CreateReviewParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Rating    int32       `json:"rating"`
	Comment   *string     `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ProductID,
		arg.UserID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, product_id, user_id, rating, comment, created_at FROM reviews WHERE id = $1
`

func (q *Queries) GetReviewByID(ctx context.Context, id pgtype.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewsByProductID = `-- name: GetReviewsByProductID :many
SELECT r.id, r.product_id, r.user_id, r.rating, r.comment, r.created_at, u.first_name, u.last_name, u.avatar 
FROM reviews r
JOIN users u ON u.id = r.user_id
WHERE r.product_id = $1
ORDER BY r.created_at DESC
`

type GetReviewsByProductIDRow struct {
	ID        pgtype.UUID      `json:"id"`
	ProductID pgtype.UUID      `json:"product_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Rating    int32            `json:"rating"`
	Comment   *string          `json:"comment"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	FirstName *string          `json:"first_name"`
	LastName  *string          `json:"last_name"`
	Avatar    *string          `json:"avatar"`
}

func (q *Queries) GetReviewsByProductID(ctx context.Context, productID pgtype.UUID) ([]GetReviewsByProductIDRow, error) {
	rows, err := q.db.Query(ctx, getReviewsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReviewsByProductIDRow{}
	for rows.Next() {
		var i GetReviewsByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserReviewForProduct = `-- name: GetUserReviewForProduct :one
SELECT id, product_id, user_id, rating, comment, created_at FROM reviews WHERE product_id = $1 AND user_id = $2
`

type GetUserReviewForProductParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetUserReviewForProduct(ctx context.Context, arg GetUserReviewForProductParams) (Review, error) {
	row := q.db.QueryRow(ctx, getUserReviewForProduct, arg.ProductID, arg.UserID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}
