// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sitemap.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCategorySlugs = `-- name: ListCategorySlugs :many
SELECT slug, updated_at FROM categories WHERE is_active = true ORDER BY updated_at DESC
`

type ListCategorySlugsRow struct {
	Slug      *string          `json:"slug"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListCategorySlugs(ctx context.Context) ([]ListCategorySlugsRow, error) {
	rows, err := q.db.Query(ctx, listCategorySlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategorySlugsRow{}
	for rows.Next() {
		var i ListCategorySlugsRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionSlugs = `-- name: ListCollectionSlugs :many
SELECT slug, updated_at FROM collections WHERE is_active = true ORDER BY updated_at DESC
`

type ListCollectionSlugsRow struct {
	Slug      string           `json:"slug"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListCollectionSlugs(ctx context.Context) ([]ListCollectionSlugsRow, error) {
	rows, err := q.db.Query(ctx, listCollectionSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionSlugsRow{}
	for rows.Next() {
		var i ListCollectionSlugsRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductSlugs = `-- name: ListProductSlugs :many
SELECT slug, updated_at FROM products WHERE is_active = true ORDER BY updated_at DESC
`

type ListProductSlugsRow struct {
	Slug      string           `json:"slug"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListProductSlugs(ctx context.Context) ([]ListProductSlugsRow, error) {
	rows, err := q.db.Query(ctx, listProductSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductSlugsRow{}
	for rows.Next() {
		var i ListProductSlugsRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
