// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (user_id, label, contact_email, phone, first_name, last_name, delivery_zone, division, district, thana, address_line, landmark, postal_code, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, user_id, label, contact_email, phone, first_name, last_name, delivery_zone, division, district, thana, address_line, landmark, postal_code, is_default, created_at
`

type CreateAddressParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Label        *string     `json:"label"`
	ContactEmail *string     `json:"contact_email"`
	Phone        *string     `json:"phone"`
	FirstName    *string     `json:"first_name"`
	LastName     *string     `json:"last_name"`
	DeliveryZone *string     `json:"delivery_zone"`
	Division     *string     `json:"division"`
	District     *string     `json:"district"`
	Thana        *string     `json:"thana"`
	AddressLine  *string     `json:"address_line"`
	Landmark     *string     `json:"landmark"`
	PostalCode   *string     `json:"postal_code"`
	IsDefault    bool        `json:"is_default"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.Label,
		arg.ContactEmail,
		arg.Phone,
		arg.FirstName,
		arg.LastName,
		arg.DeliveryZone,
		arg.Division,
		arg.District,
		arg.Thana,
		arg.AddressLine,
		arg.Landmark,
		arg.PostalCode,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.ContactEmail,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.DeliveryZone,
		&i.Division,
		&i.District,
		&i.Thana,
		&i.AddressLine,
		&i.Landmark,
		&i.PostalCode,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, role, first_name, last_name, avatar)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, role, first_name, last_name, avatar, created_at, updated_at, phone
`

type CreateUserParams struct {
	Email     string  `json:"email"`
	Role      string  `json:"role"`
	FirstName *string `json:"first_name"`
	LastName  *string `json:"last_name"`
	Avatar    *string `json:"avatar"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Role,
		arg.FirstName,
		arg.LastName,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses WHERE id = $1 AND user_id = $2
`

type DeleteAddressParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) error {
	_, err := q.db.Exec(ctx, deleteAddress, arg.ID, arg.UserID)
	return err
}

const getAddressesByUserID = `-- name: GetAddressesByUserID :many
SELECT id, user_id, label, contact_email, phone, first_name, last_name, delivery_zone, division, district, thana, address_line, landmark, postal_code, is_default, created_at FROM addresses WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAddressesByUserID(ctx context.Context, userID pgtype.UUID) ([]Address, error) {
	rows, err := q.db.Query(ctx, getAddressesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.ContactEmail,
			&i.Phone,
			&i.FirstName,
			&i.LastName,
			&i.DeliveryZone,
			&i.Division,
			&i.District,
			&i.Thana,
			&i.AddressLine,
			&i.Landmark,
			&i.PostalCode,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, token, user_id, expires_at, created_at, revoked, device FROM refresh_tokens WHERE token = $1 AND revoked = false
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
		&i.Device,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, role, first_name, last_name, avatar, created_at, updated_at, phone FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, role, first_name, last_name, avatar, created_at, updated_at, phone FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = true WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, token)
	return err
}

const saveRefreshToken = `-- name: SaveRefreshToken :one
INSERT INTO refresh_tokens (token, user_id, expires_at, device)
VALUES ($1, $2, $3, $4)
RETURNING id, token, user_id, expires_at, created_at, revoked, device
`

type SaveRefreshTokenParams struct {
	Token     string           `json:"token"`
	UserID    pgtype.UUID      `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Device    *string          `json:"device"`
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, saveRefreshToken,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
		arg.Device,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
		&i.Device,
	)
	return i, err
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE addresses
SET label = $2, contact_email = $3, phone = $4, first_name = $5, last_name = $6, delivery_zone = $7, division = $8, district = $9, thana = $10, address_line = $11, landmark = $12, postal_code = $13, is_default = $14
WHERE id = $1 AND user_id = $15
RETURNING id, user_id, label, contact_email, phone, first_name, last_name, delivery_zone, division, district, thana, address_line, landmark, postal_code, is_default, created_at
`

type UpdateAddressParams struct {
	ID           pgtype.UUID `json:"id"`
	Label        *string     `json:"label"`
	ContactEmail *string     `json:"contact_email"`
	Phone        *string     `json:"phone"`
	FirstName    *string     `json:"first_name"`
	LastName     *string     `json:"last_name"`
	DeliveryZone *string     `json:"delivery_zone"`
	Division     *string     `json:"division"`
	District     *string     `json:"district"`
	Thana        *string     `json:"thana"`
	AddressLine  *string     `json:"address_line"`
	Landmark     *string     `json:"landmark"`
	PostalCode   *string     `json:"postal_code"`
	IsDefault    bool        `json:"is_default"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.Label,
		arg.ContactEmail,
		arg.Phone,
		arg.FirstName,
		arg.LastName,
		arg.DeliveryZone,
		arg.Division,
		arg.District,
		arg.Thana,
		arg.AddressLine,
		arg.Landmark,
		arg.PostalCode,
		arg.IsDefault,
		arg.UserID,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.ContactEmail,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.DeliveryZone,
		&i.Division,
		&i.District,
		&i.Thana,
		&i.AddressLine,
		&i.Landmark,
		&i.PostalCode,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, role = $3, first_name = $4, last_name = $5, avatar = $6
WHERE id = $1
RETURNING id, email, role, first_name, last_name, avatar, created_at, updated_at, phone
`

type UpdateUserParams struct {
	ID        pgtype.UUID `json:"id"`
	Email     string      `json:"email"`
	Role      string      `json:"role"`
	FirstName *string     `json:"first_name"`
	LastName  *string     `json:"last_name"`
	Avatar    *string     `json:"avatar"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Role,
		arg.FirstName,
		arg.LastName,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET first_name = $2, last_name = $3, phone = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, email, role, first_name, last_name, avatar, created_at, updated_at, phone
`

type UpdateUserProfileParams struct {
	ID        pgtype.UUID `json:"id"`
	FirstName *string     `json:"first_name"`
	LastName  *string     `json:"last_name"`
	Phone     *string     `json:"phone"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
	)
	return i, err
}
